README.md
recipe/meta.yaml

ENH put a dash in the name

---

recipe/meta.yaml

Add firefly-client and update treecorr/pybind11 restriction

---

recipe/meta.yaml

Add documenteer

---

.ci_support/linux_64_.yaml
recipe/activate.sh
recipe/build.sh
recipe/deactivate.sh
recipe/meta.yaml

documenteer alone is insufficient.
activate/deactivate scripts allow proper handling of EUPS_PATH.
Checklist

Replace documenteer and add activate/deactivate scripts.

---

recipe/meta.yaml

This enables the use of Python 3.8 features.
Checklist

Pin flake8 to newer version.

---

recipe/meta.yaml

Add dustmaps requirement

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Note that boost and numpy sometimes change ABI with even minor versions.
Checklist

Pin major versions of C++-linked packages.

---

recipe/meta.yaml

Pin scikit-image to avoid problem with read-only environment.

---

.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
recipe/meta.yaml

Unpin several packages.

---

recipe/meta.yaml

DM-29262: Pin sqlalchemy to avoid incompatible API change.

---

recipe/meta.yaml

DM-29521: Pin sqlalchemy and sqlite.

---

recipe/meta.yaml

DM-29521: Pin sqlite to avoid UNION ALL problem.

---

.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

DM-29608: Add pydantic (RFC-770).

---

README.md
recipe/meta.yaml

DM-30033: Add alembic and tweak some pins.

---

.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
README.md
recipe/meta.yaml

Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #26.
Here's a checklist to do before merging.
Fixes #26

MNT: rerender

---

.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
build-locally.py
recipe/meta.yaml

DM-30158: Pin macOS compilers and click.

---

.azure-pipelines/azure-pipelines-linux.yml
recipe/meta.yaml

DM-30997: Pin galsim minor version.

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/osx_64_.yaml
recipe/meta.yaml

Bump build number.

---

recipe/meta.yaml

Pin to versions that work with v22.

---

recipe/meta.yaml

DM-31101: Pin networkx due to None node handling.

---

recipe/meta.yaml

DM-31233: Add PanDA packages.

---

.gitattributes
README.md
build-locally.py
recipe/meta.yaml

DM-32591: Add pre-existing inflection dependency.

---

.ci_support/linux_64_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/activate.sh
recipe/deactivate.sh
recipe/meta.yaml

Make (de)activate POSIX-compatible.

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
conda-forge.yml
recipe/meta.yaml

DM-33347: Pin moto to < 3.0 as needed by daf_butler

---

LICENSE.txt
recipe/meta.yaml

DM-33398: Pin pytables to get mock.

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
LICENSE.txt
recipe/meta.yaml

DM-33399: Change how we depend on compilers.

---

recipe/meta.yaml

This resolves this comment: https://github.com/conda-forge/rubinenv-feedstock/pull/49#discussion_r792527047
Checklist

Add compilers package back in.

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

DM-33399: Fix how we depend on compilers.

---

recipe/meta.yaml

DM-33404: Add prmon to environment 0.8.0

---

recipe/meta.yaml

Do not allow coverage 6.3 in environment.

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Change channel target for dev build.

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_aarch64_.yaml
.scripts/build_steps.sh
README.md
conda-forge.yml
recipe/meta.yaml

Checklist
To make this solve, move cfitsio pin to 3.10 and numpy to 1.21.  Also try to enable the linux_aarch64 build.

DM-33469: Add python=3.10 dev environment

---

recipe/meta.yaml

Update to python=3.10, cfitsio=4, numpy=1.21

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Implements RFC-824 and RFC-826.
Checklist

DM-33545: Add spherematch and pin cfitsio=4.

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
conda-forge.yml
recipe/conda_build_config.yaml
recipe/meta.yaml

DM-33994: Add threadpoolctl (RFC-835).

---

recipe/meta.yaml

DM-34350: Add minimum version on moto to prevent crazy solves.

---

recipe/meta.yaml

ENH try again for pins

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.travis.yml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

* Still python 3.10.
* Add PyLD, skyproj.
* Add rubin-env-extras output including packages from sciplat-lab,
shared_stack, sims, and add in imagemagick and ffmpeg.
* Update cfitsio to 4.1.0 and flake8 to 4.0.
Checklist

DM-34610: Update rubin-env to v4 and add rubin-env-extras (dev branch).

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.circleci/config.yml
recipe/meta.yaml

DM-35038: Update IDDS to 0.11.0 or better.

---

recipe/meta.yaml

DM-35083: Add restriction to spherematch.

---

recipe/meta.yaml

Pin pybind11 at <2.10.

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

* cassandra-driver
* getcalspec
* hpgeom
* yaml-cpp
Checklist

DM-35626: Add packages for rubin-env 4.1.0.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.github/workflows/automerge.yml
.github/workflows/webservices.yml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Merge 4.1.0 changes.
Remove inflection.
Unpin packages now that code has been fixed.
Update version and build number.
Checklist

Prepare for 5.0.0.

---

recipe/meta.yaml

DM-35682: Add selectors for non-osx-arm64.

---

recipe/meta.yaml

DM-35778: Pin scipy <1.9.

---

recipe/meta.yaml

Forgot to pull upstream before making the last ticket branch.
Checklist

Properly bump build number.

---

.ci_support/osx_64_.yaml
recipe/meta.yaml

Constrain galsim <2.4.0

---

recipe/meta.yaml

Add jupyterlab-variableinspector

---

.ci_support/osx_64_.yaml
recipe/meta.yaml

DM-36267: Pin matplotlib < 3.6.

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

Create v4.0.2 and pin galsim and stomp.py

---

.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Add explicit fortran pin to prevent unintended updates.

---

recipe/meta.yaml

DM-36736: Add wget to rubin-env-rsp.

---

.ci_support/osx_64_.yaml
recipe/meta.yaml

Create Rubinenv 4.0.3

---

recipe/meta.yaml

Checklist
* [] Bumped the build number (if the version is unchanged)

pin matplotlib-base, create rubinenv 0.8.2

---

recipe/meta.yaml

Add wget (DM-36736).

---

recipe/meta.yaml

DM-37048: Pin minimum panel to fix bokeh incompatibility.

---

.ci_support/osx_arm64_.yaml
.circleci/config.yml
.github/workflows/automerge.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

Add rubin env rsp

---

.ci_support/osx_arm64_.yaml
recipe/meta.yaml

pin lmfit for 0.8.x

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Also add astrowidgets, ipympl, jupyterlab, and jupyterlab_server to -developer.
Checklist

DM-37324: Add humanize and parsl.

---

recipe/meta.yaml

DM-37350: Pin getcalspec>=0.1.6.

---

recipe/meta.yaml

DM-37435: Pin coverage at <7.

---

recipe/meta.yaml

Pin ginga due to astrowidgets incompatibility.

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Require matplotlib <3.7.0

---

recipe/meta.yaml

Pin iminuit

---

recipe/meta.yaml

Pin iminuit to < 2.20

---

recipe/meta.yaml

DM-38438: Pin doxygen to avoid segfault.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/create_conda_build_artifacts.sh
.scripts/run_osx_build.sh
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Update numpy pin to 1.23 on dev branch.

---

recipe/meta.yaml

DM-38550: Pin pandas to <2.

---

recipe/meta.yaml

DM-38575: Pin scikit-image <0.20.

---

recipe/meta.yaml

DM-38623: Pin photutils at <1.7.

---

.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

DM-38624: Cherry-pick doxygen pin to release branch.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

DM-38719: Add explicit frozendict dependency.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Update dev to match 6.0.0 release candidate.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.github/CODEOWNERS
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

DM-38738: Merge dev with main for rubin-env 6.0.0.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/create_conda_build_artifacts.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

Pin photutils version <1.7.0

---

recipe/meta.yaml

Add pins from 5.1.0 to 5.0.x

---

recipe/meta.yaml

DM-39313: Add lsst-efd-client.

---

recipe/meta.yaml

Update ndarray version

---

recipe/meta.yaml

Unpin matplotlib-base.

---

recipe/meta.yaml

DM-39810: Pin scipy <1.11.

---

recipe/meta.yaml

Do more of DM-39804 on dev.

---

recipe/meta.yaml

Fix some package churn

---

recipe/meta.yaml

Pin pydantic

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

Pin pydantic for v4.0.x

---

recipe/meta.yaml

Pin pydantic to version 1

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/run_osx_build.sh
recipe/conda_build_config.yaml
recipe/meta.yaml

Add pytest-vcr, fitsverify, and update pins.

---

recipe/meta.yaml

Increase minimum jupyterlab pin.

---

recipe/meta.yaml

DM-40043: Pin pybind11 to <2.11.

---

.azure-pipelines/azure-pipelines-linux.yml
recipe/meta.yaml

DM-40295: Force mkl to retain binary compatibility.

---

recipe/meta.yaml

Pin fastavro for rubinenv 5.0.1

---

recipe/meta.yaml

Pin pyarrow <13.

---

recipe/meta.yaml

DM-40636: Pin pandas <2.1.

---

recipe/meta.yaml

Checklist
Chris Walter wanted awkward-pandas, and while attempting to do that, we found out that awkward-numba has been rolled into awkward and was holding back adoption of current awkward.

tickets/DM-40875: remove awkward-numba, add awkward-pandas

---

recipe/meta.yaml

DM-41342: Add httpx to -rsp

---

recipe/meta.yaml

Checklist
Migrates JupyterLab to version 4, which has some updated dependencies.

migrate to JupyterLab 4

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

Remove pdbpp which is broken and unsupported on python>3.10.

---

recipe/meta.yaml

Add sbpy to RSP

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.travis.yml
README.md
recipe/meta.yaml

Pin networkx v5 for rubinenv v5.0.1

---

recipe/meta.yaml

force pyvo to at least 1.4.2

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

DM-41893: Avoid boto3 1.33.0.

---

recipe/meta.yaml

Pin back dask to avoid pyarrow warning

---

recipe/meta.yaml

DM-41872: Pin openssl to avoid libpq segv

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.travis.yml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Further updates for rubin-env 8 as a result of testing.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

DM-42147: Further updates for rubin-env 8.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Checklist
This should resolve a conflict with libmamba brought in by rubin-env-rsp.

DM-42147 (cont.): Bump yaml-cpp version.

---

recipe/meta.yaml

DM-42147 (cont): Move galsim; add >= pins (and pin HTCondor to LTS).

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

DM-42147: Release version 8.0.0.

---

.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
recipe/meta.yaml

DM-42582: Pin scipy to <1.12.

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

Use default build of clang on osx.

---

recipe/meta.yaml

DM-42698: Pin moto <5.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
recipe/meta.yaml

Pin moto < 5

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
build-locally.py
recipe/meta.yaml

DM-43113: Constrain mpi4py builds.

---

recipe/meta.yaml

DM-43144: Pin pytest <8.1.0.

---

recipe/meta.yaml

DM-43164: Add rubin-scheduler, rubin-sim, schedview.

---

recipe/meta.yaml

Pin urllib3 <2 for 4.0.x

---

recipe/meta.yaml

Pin urllib3 <2 for 5.0.x

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
build-locally.py
recipe/meta.yaml

DM-43113-v7:  Constrain mpi4py builds

---

recipe/meta.yaml

DM-44687: Avoid bad git version.

---

recipe/meta.yaml

DM-45092: Pin matplotlib < 3.9.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Eliminate packages that are not available on aarch64.

---

recipe/meta.yaml

Pin piff to 1.3.

---

recipe/meta.yaml

Pin piff to 1.3.3.

---

recipe/meta.yaml

Fix git version and pin some others.

---

recipe/meta.yaml

Fix build number.

---

.scripts/build_steps.sh
recipe/meta.yaml

Allow sorcha on aarch64.

---

.scripts/build_steps.sh
recipe/meta.yaml

Add pkg-config

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/migrations/starlink_ast9211.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Rebuild for starlink_ast 9.2.11

---

recipe/meta.yaml

Fix pkg config

---

recipe/meta.yaml

DM-43326: Add jax, mistakenly left out of build 0.

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/migrations/starlink_ast9211.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

DM-45920: Pin setuptools <=72.1.0 for rubinenv 9

---

recipe/meta.yaml

Checklist
* [ X Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

Move pkg-config to the correct section

---

recipe/meta.yaml

Pin Pytorch for aarch64

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
recipe/meta.yaml

DM-47491: Pin astropy <6.1.5.

---

build-locally.py
recipe/meta.yaml

Unpin black, replace nb-black with black-jupyter

---

recipe/meta.yaml

Pin skyproj to <2

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.scripts/run_osx_build.sh
build-locally.py
recipe/meta.yaml

Pin skyproj to <2 (rubinenv 8)

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Pin astroquery <0.4.8 for rubin-env v8.0.x

---

recipe/meta.yaml

Checklist
* [X ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X ] Bumped the build number (if the version is unchanged)
* [X ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X ] Ensured the license file is being packaged.

Pin back dask for datashader

---

.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Bump libBoost, starlink_ast and htcondor

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.gitignore
recipe/conda_build_config.yaml
recipe/meta.yaml

Pin minuit to 6.22.06

---

.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
.gitignore
recipe/conda_build_config.yaml
recipe/meta.yaml

Pin Minuit2 6.34, update parsl and remove Nose

---

recipe/meta.yaml

Pin matplotlib to <3.10

---

recipe/meta.yaml

Add pz-rail-base and pz-rail-sklearn

---

recipe/conda_build_config.yaml
recipe/meta.yaml

- **Pin astroquery <0.4.8**
- **MNT: Re-rendered with conda-build 25.1.1, conda-smithy 3.45.4, and conda-forge-pinning 2025.01.28.22.50.30**
Checklist

Pin astroquery <0.4.8.

---

recipe/meta.yaml

Checklist
Implements RFC#1067 cf https://rubinobs.atlassian.net/browse/RFC-1067

Add mermaid-py

---

recipe/meta.yaml

Pin minimal versions of new packages

---

recipe/meta.yaml

Move version to dev1 from dev

---

recipe/meta.yaml

Update to 9.1 and set confluent kafka >=2

---

recipe/meta.yaml

Pinning formatting and astropy-base

---

recipe/meta.yaml

Add astroplan >=0.10.1 to rubin-env 

---

recipe/meta.yaml

Add maturin and bumping version to latest

---

recipe/meta.yaml

Update to version dev2

---

.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
conda-forge.yml
recipe/meta.yaml

10.0.0dev3

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/migrations/numpy2.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
README.md
conda-forge.yml
recipe/conda_build_config.yaml
recipe/meta.yaml

Create rubin env 10.0.0

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Checklist
This is the same as #280 ; dash crept back in in 10.0 and should not have

remove dash from rsp

---

recipe/meta.yaml

Pin pytest-profiling to 1.8.1

---

recipe/meta.yaml

Add paramiko to rubin-env

---

recipe/meta.yaml

DM-49560: Pin pyarrow <18

---

recipe/meta.yaml

As instructed in [RFC-1082](https://rubinobs.atlassian.net/browse/RFC-1082)
Checklist

DM-49726: Pin ngmix >= 2.4.0

---

recipe/meta.yaml

DM-49778: Add additional clang tools

---

.scripts/run_docker_build.sh
build-locally.py
recipe/meta.yaml

- **Remove pin <9 on ipython**
- **MNT: Re-rendered with conda-build 25.1.2, conda-smithy 3.47.1, and conda-forge-pinning 2025.04.09.18.25.10**
Checklist

Pin ipython !=9.0.0

---

.ci_support/migrations/cfitsio462.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

- **Add Urllib and botocore. They are indirect Dependencies**
- **MNT: Re-rendered with conda-build 25.4.2, conda-smithy 3.48.1, and conda-forge-pinning 2025.05.07.15.57.42**
Checklist

Add indirect dependencies

---

recipe/meta.yaml

Add indirect dependencies zstandard

---

recipe/meta.yaml

DM-80823: Pin click < 8.2

---

.gitignore
.scripts/run_docker_build.sh
build-locally.py
recipe/meta.yaml

Pin for env9

---

recipe/meta.yaml

DM-51110: Add python-gfal2 to rubin-env-developer.

---

recipe/meta.yaml

DM-51110a: Add gfal2-util for commands.

---

recipe/meta.yaml

Update to rubin 11

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/migrations/starlink_ast9214.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

Dev: Fix version pinning of starlink-ast 9.2.14

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/recipe.yaml

Update dev to Python 3.13
