conda-forge/rubinenv-feedstock

recipe/meta.yaml

Adds eups to the recipe. Uses matplotlib-base to avoid pyqt on linux.
Checklist

Add eups, use matplotlib-base

---

recipe/meta.yaml

Checklist
mpich is removed because it may be tough to get a solution otherwise. This may break jobs against slurm verification cluster at NCSA (mpich 3.3 regression fixed in yet-to-be-released mpich 3.4) but should be fine otherwise.

Update to python 3.8. Remove mpich restriction

---

recipe/meta.yaml

DM-30992: Pin pandas due to uint64 disallowal.

---

recipe/meta.yaml

- Add minimum pins for IDDS components (already proposed as 0.7.1).
- Remove pins from click, galsim, pandas, networkx, and sqlite as documented on https://confluence.lsstcorp.org/display/DM/DM+Third+Party+Software; adjust scikit-image pin to allow new releases.
- Add requested dependencies for Spectractor (RFC-800).
- Add prmon for PanDA batch process monitoring (DM-32579, restricted to Linux-only).
Checklist

DM-33380: Create rubin-env 1.0.0.

---

recipe/meta.yaml

This seems to break on Jenkins with multiple processes and NFS
mounts.
Checklist

Do not allow coverage 6.3 in environment

---

.azure-pipelines/azure-pipelines-osx.yml
recipe/meta.yaml

ephem is not required for sims
Checklist

Remove ephem from list of sims packages in rubin-env-extras

---

recipe/meta.yaml

A breaking change was made to the class organization, preventing imports by ctrl_bps_parsl.
Checklist

DM-37820: Pin parsl to 1.2.

---

recipe/meta.yaml

This is for [RFC-922](https://jira.lsstcorp.org/browse/RFC-922) and [RFC-923](https://jira.lsstcorp.org/browse/RFC-923).  These packages were already in the environment, but we are now explicitly depending on them.
Checklist

DM-39006: Make importlib_resources and fitsio explicit.

---

recipe/meta.yaml

spectractor used a deprecated keyword in the photutils API that is now gone.  Pin photutils until this can be fixed.
Checklist

DM-39291: Pin photutils to 1.7.

---

recipe/meta.yaml

Since this is an addition to `-rsp` only, and that is always containerized, there are no backward or forward compatibility issues, and a build number bump is sufficient.
Checklist

DM-38723: Add gh package to -rsp.

---

recipe/meta.yaml

Removing rucio-clients frees up a number of dependencies. Increasing the minimum pin for jupyterlab ensures proper versions of it and jupyterlab_server for the RSP.
Checklist

DM-40021: Fix dependency downgrades in rubin-env 7.0.0.

---

recipe/meta.yaml

Checklist
JupyterLab in the RSP was failing to execute any kernels because of duplication of jupyter-dash.  The functionality in jupyter-dash has been rolled up into dash.

Remove jupyter-dash--contents in dash now

---

recipe/conda_build_config.yaml
recipe/meta.yaml

Update for testing rubin-env 8.

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

1.3 currently breaks difference imaging.
Checklist

Pin lmfit to < 1.3

---

recipe/meta.yaml

DM-46237-hotfix: Pin Pytorch to <= 2.3.1 for aarch64

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.scripts/run_osx_build.sh
recipe/meta.yaml

This PR adds a dependency on the Python [deepdiff](https://pypi.org/project/deepdiff/) package for supporting new functionality in [Felis](https://github.com/lsst/felis).
This is already a transitive dependency of `idds-common`, so I have not incremented the version. It should be possible to handle this change as a build update rather than a new release.
Checklist

DM-47922: Add deepdiff to run-like dependencies

---

recipe/meta.yaml

Checklist
dash needs a Lab rebuild, and our Github Actions machine doesn't have enough memory to do that.  I kinda think we don't need dash in the first place, since it's mostly for building standalone applications.

Remove dash from rsp env

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Checklist
This fixes the rerendering problem.  Apparently there is a new required `is_python_min` zip key that needs to go in `conda_build_config.yaml` and it seems that there must be a related migration bug related to this.  cc @beckermr

Pin astroquery <0.4.8 and fix rerendering

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/migrations/starlink_ast9214.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/recipe.yaml

- **Add lsst-documenteer-guide to recipe**
- **Update starlink_ast to 9.2.14**
- **MNT: Re-rendered with conda-smithy 3.52.2 and conda-forge-pinning 2025.09.17.06.41.22**
Checklist

DM-52559:Fix Starlink_ast and add missing documenteer dep

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
README.md
conda-forge.yml
recipe/recipe.yaml

Checklist
This ensure eups is compatible with latest LSST server.

fix: update eups pin to 2.2.14
